# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910-1"
    hooks:
    -   id: mypy
-   repo: https://github.com/psf/black
    rev: "21.9b0"
    hooks:
    -   id: black
-   repo:  https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        args: ["--count", "--select=E9,F63,F7,F82", "--show-source", "--statistics"]
    -   id: flake8
        args: ["--count", "--exit-zero", "--max-complexity=5", "--max-line-length=88", "--ignore=E203", "--statistics"]
-   repo:  https://github.com/jendrikseipp/vulture 
    rev: "v2.3"
    hooks:
    -   id: vulture
